# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class LdapAuthResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cr=None, result=None):  # noqa: E501
        """LdapAuthResponse - a model defined in OpenAPI

        :param cr: The cr of this LdapAuthResponse.  # noqa: E501
        :type cr: str
        :param result: The result of this LdapAuthResponse.  # noqa: E501
        :type result: str
        """
        self.openapi_types = {
            'cr': str,
            'result': str
        }

        self.attribute_map = {
            'cr': 'cr',
            'result': 'result'
        }

        self._cr = cr
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'LdapAuthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ldapAuth_response of this LdapAuthResponse.  # noqa: E501
        :rtype: LdapAuthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cr(self):
        """Gets the cr of this LdapAuthResponse.


        :return: The cr of this LdapAuthResponse.
        :rtype: str
        """
        return self._cr

    @cr.setter
    def cr(self, cr):
        """Sets the cr of this LdapAuthResponse.


        :param cr: The cr of this LdapAuthResponse.
        :type cr: str
        """

        self._cr = cr

    @property
    def result(self):
        """Gets the result of this LdapAuthResponse.


        :return: The result of this LdapAuthResponse.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this LdapAuthResponse.


        :param result: The result of this LdapAuthResponse.
        :type result: str
        """

        self._result = result
