# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class VerifyTokenResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cr=None, result=None, username=None):  # noqa: E501
        """VerifyTokenResponse - a model defined in OpenAPI

        :param cr: The cr of this VerifyTokenResponse.  # noqa: E501
        :type cr: str
        :param result: The result of this VerifyTokenResponse.  # noqa: E501
        :type result: str
        :param username: The username of this VerifyTokenResponse.  # noqa: E501
        :type username: str
        """
        self.openapi_types = {
            'cr': str,
            'result': str,
            'username': str
        }

        self.attribute_map = {
            'cr': 'cr',
            'result': 'result',
            'username': 'username'
        }

        self._cr = cr
        self._result = result
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'VerifyTokenResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The verifyToken_response of this VerifyTokenResponse.  # noqa: E501
        :rtype: VerifyTokenResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cr(self):
        """Gets the cr of this VerifyTokenResponse.


        :return: The cr of this VerifyTokenResponse.
        :rtype: str
        """
        return self._cr

    @cr.setter
    def cr(self, cr):
        """Sets the cr of this VerifyTokenResponse.


        :param cr: The cr of this VerifyTokenResponse.
        :type cr: str
        """

        self._cr = cr

    @property
    def result(self):
        """Gets the result of this VerifyTokenResponse.


        :return: The result of this VerifyTokenResponse.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this VerifyTokenResponse.


        :param result: The result of this VerifyTokenResponse.
        :type result: str
        """

        self._result = result

    @property
    def username(self):
        """Gets the username of this VerifyTokenResponse.


        :return: The username of this VerifyTokenResponse.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this VerifyTokenResponse.


        :param username: The username of this VerifyTokenResponse.
        :type username: str
        """

        self._username = username
